# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/ulp_inst_0_axi_noc_kernel0_0.xci
# IP: The module: 'ulp_inst_0_axi_noc_kernel0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/bd_0ad1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ad1 || ORIG_REF_NAME==bd_0ad1} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_0/bd_0ad1_M02_INI_stub_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ad1_M02_INI_stub_nmu_0 || ORIG_REF_NAME==bd_0ad1_M02_INI_stub_nmu_0} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_1/bd_0ad1_S00_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ad1_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_0ad1_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_2/bd_0ad1_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ad1_const_0_0 || ORIG_REF_NAME==bd_0ad1_const_0_0} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_3/bd_0ad1_S01_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ad1_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_0ad1_S01_AXI_nmu_0} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_4/bd_0ad1_stub_clock_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ad1_stub_clock_0 || ORIG_REF_NAME==bd_0ad1_stub_clock_0} -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_0/xdc/bd_0ad1_M02_INI_stub_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ad1_M02_INI_stub_nmu_0 || ORIG_REF_NAME==bd_0ad1_M02_INI_stub_nmu_0} -quiet] {/bd_0ad1_M02_INI_stub_nmu_0_top_INST } ]/bd_0ad1_M02_INI_stub_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_1/xdc/bd_0ad1_S00_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ad1_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_0ad1_S00_AXI_nmu_0} -quiet] {/bd_0ad1_S00_AXI_nmu_0_top_INST } ]/bd_0ad1_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_3/xdc/bd_0ad1_S01_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ad1_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_0ad1_S01_AXI_nmu_0} -quiet] {/bd_0ad1_S01_AXI_nmu_0_top_INST } ]/bd_0ad1_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/ulp_inst_0_axi_noc_kernel0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_inst_0_axi_noc_kernel0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/ulp_inst_0_axi_noc_kernel0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_inst_0_axi_noc_kernel0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/ulp_inst_0_axi_noc_kernel0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_inst_0_axi_noc_kernel0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/ulp_inst_0_axi_noc_kernel0_0.xci
# IP: The module: 'ulp_inst_0_axi_noc_kernel0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/bd_0ad1.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ad1 || ORIG_REF_NAME==bd_0ad1} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_0/bd_0ad1_M02_INI_stub_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ad1_M02_INI_stub_nmu_0 || ORIG_REF_NAME==bd_0ad1_M02_INI_stub_nmu_0} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_1/bd_0ad1_S00_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ad1_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_0ad1_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_2/bd_0ad1_const_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ad1_const_0_0 || ORIG_REF_NAME==bd_0ad1_const_0_0} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_3/bd_0ad1_S01_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ad1_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_0ad1_S01_AXI_nmu_0} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_4/bd_0ad1_stub_clock_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ad1_stub_clock_0 || ORIG_REF_NAME==bd_0ad1_stub_clock_0} -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_0/xdc/bd_0ad1_M02_INI_stub_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ad1_M02_INI_stub_nmu_0 || ORIG_REF_NAME==bd_0ad1_M02_INI_stub_nmu_0} -quiet] {/bd_0ad1_M02_INI_stub_nmu_0_top_INST } ]/bd_0ad1_M02_INI_stub_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_1/xdc/bd_0ad1_S00_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ad1_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_0ad1_S00_AXI_nmu_0} -quiet] {/bd_0ad1_S00_AXI_nmu_0_top_INST } ]/bd_0ad1_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/bd_0/ip/ip_3/xdc/bd_0ad1_S01_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ad1_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_0ad1_S01_AXI_nmu_0} -quiet] {/bd_0ad1_S01_AXI_nmu_0_top_INST } ]/bd_0ad1_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/ulp_inst_0_axi_noc_kernel0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_inst_0_axi_noc_kernel0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/ulp_inst_0_axi_noc_kernel0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_inst_0_axi_noc_kernel0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/ulp_inst_0_axi_noc_kernel0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_inst_0_axi_noc_kernel0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
