# This file was automatically generated by Vpl
# utilization reports
report_utilization_impl true "setup_aie sink_from_aie" "placed" "top_i/ulp" $input_dir $vivado_output_dir
collect_compute_unit_utilization "top_i/ulp"
