/********************************************* Disclaimer *********************************************/
/* This file is generated by aiecompiler 2022.2. */
/* Changes to this file may cause incorrect behavior and will be lost if aiecompiler is invoked again.*/

/************************** Constants/Macros *****************************/
#define HW_GEN                   XAIE_DEV_GEN_AIE
#define XAIE_NUM_ROWS            9
#define XAIE_NUM_COLS            50
#define XAIE_BASE_ADDR           0x20000000000
#define XAIE_COL_SHIFT           23
#define XAIE_ROW_SHIFT           18
#define XAIE_SHIM_ROW            0
#define XAIE_MEM_TILE_ROW_START  0
#define XAIE_MEM_TILE_NUM_ROWS   0
#define XAIE_AIE_TILE_ROW_START  1
#define XAIE_AIE_TILE_NUM_ROWS   8
#define FOR_WRITE                0
#define FOR_READ                 1

/***************************** Includes *********************************/
#include <fstream>
#include <adf.h>
extern "C"
{
  #include <xaiengine.h>
}
#include "adf/adf_api/AIEControlConfig.h"

XAie_InstDeclare(DevInst, &ConfigPtr);   // Declare global device instance


/************************** Functions/APIs *****************************/
  adf::return_code broadcastConfigForCoreEnable()
  {
	if(!adf::reserveBroadcastchannelForEnablingCores())
	{
		std::cerr << "ERROR: Failed to reserve Broadcast channels for enabling core.\n";
		return adf::return_code::aie_driver_error;
	}
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(0, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(1, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(1, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(1, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(1, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(2, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(2, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(2, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(2, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(3, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(3, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(3, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(3, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(4, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(4, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(4, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(4, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(5, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(5, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(5, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(5, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(6, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(6, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(6, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(6, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(7, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(7, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(7, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(7, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(8, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(8, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(8, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(8, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(9, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(9, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(9, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(9, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(10, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(10, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(10, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(10, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(11, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(11, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(11, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(11, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(12, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(12, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(12, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(12, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(13, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(13, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(13, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(13, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(14, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(14, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(14, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(14, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(15, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(15, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(15, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(15, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(16, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(16, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(16, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(16, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(17, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(17, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(17, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(17, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(18, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(18, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(18, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(18, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(19, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(19, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(19, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(19, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(20, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(20, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(20, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(20, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(21, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(21, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(21, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(21, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(22, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(22, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(22, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(22, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(23, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(23, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(23, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(23, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(24, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(24, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(24, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(24, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(25, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(25, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(25, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(25, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(26, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(26, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(26, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(26, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(27, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(27, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(27, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(27, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(28, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(28, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(28, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(28, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(29, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(29, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(29, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(29, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(30, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(30, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(30, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(30, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(31, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(31, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(31, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(31, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(32, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(32, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(32, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(32, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(33, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(33, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(33, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(33, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(34, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(34, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(34, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(34, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(35, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(35, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(35, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(35, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(36, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(36, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(36, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(36, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(37, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(37, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(37, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(37, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(38, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(38, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(38, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(38, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(39, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(39, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(39, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(39, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(40, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(40, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(40, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(40, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(41, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(41, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(41, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(41, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(42, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(42, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(42, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(42, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(43, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(43, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(43, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(43, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(44, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(44, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(44, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(44, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(45, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(45, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(45, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(45, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(46, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(46, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(46, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(46, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(47, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(47, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(47, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(47, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(48, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(48, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(48, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(48, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(49, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(49, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(49, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(49, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(24, 1), XAIE_CORE_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(24, 1), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_ALL);
	XAie_EventBroadcast(&DevInst, XAie_TileLoc(0, 0), XAIE_PL_MOD, 8, XAIE_EVENT_BROADCAST_A_8_PL);
	return adf::return_code::ok;
  }

  bool aie_graph_load_elf(const std::string& work_path, std::vector<std::string>& elfInfoPath)
  {
	#ifdef __PS_INIT_AIE__

	std::string work_dir = (work_path.empty() ?  "./Work" : work_path);
	printf("Loading elfs of graph aie_graph...\n");
	if(XAie_LoadElf(&DevInst, XAie_TileLoc(24, 1), (work_dir + "/aie/24_0/Release/24_0").c_str(), XAIE_ENABLE)!=XAIE_OK)
	{
		std::cerr << "ERROR: Failed to load elf for core(24,0)" << std::endl;
		return false;
	}
	#endif

	return true;
  }

  void aie_graph_init(const std::string& work_path)
  {

	printf("Initializing graph aie_graph...\n");
    #ifdef __PS_INIT_AIE__

	std::string work_dir = (work_path.empty() ?  "./Work" : work_path);
	// S_AIE_OUT_ch0_C24_R0 M_SOUTH_ch3_C24_R0 net1

	XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(24, 1), CORE, 0, SOUTH, 3);

	// S_SHIM_NORTH_ch3_C24 M_SHIM_SOUTH_ch0_C24 net1

	XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(24, 0), NORTH, 3, SOUTH, 0);

	// S_SHIM_SOUTH_ch2_C24 M_SHIM_NORTH_ch5_C24 net0

	XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(24, 0), SOUTH, 2, NORTH, 5);

	// S_SOUTH_ch5_C24_R0 M_AIE_IN_ch0_C24_R0 net0

	XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(24, 1), SOUTH, 5, CORE, 0);


	printf("Resetting cores of graph aie_graph...\n");
	XAie_CoreReset(&DevInst, XAie_TileLoc(24, 1));
	XAie_CoreUnreset(&DevInst, XAie_TileLoc(24, 1));
	XAie_CoreConfigureDone(&DevInst, XAie_TileLoc(24, 1));

	printf("Configuring DMAs of graph aie_graph...\n");

	printf("Configuring PL-Interface for graph aie_graph...\n");
	XAie_PlIfBliBypassDisable(&DevInst, XAie_TileLoc(24, 0), 2);
	XAie_PlToAieIntfEnable (&DevInst, XAie_TileLoc(24, 0), 2, PLIF_WIDTH_32);
	XAie_AieToPlIntfEnable (&DevInst, XAie_TileLoc(24, 0), 0, PLIF_WIDTH_32);


    #endif

	return;
  }

 void aie_graph_core_debug_halt()
  {
	printf("Putting core(s) of graph aie_graph on halt state for debugging...\n");
	XAie_CoreDebugHalt(&DevInst, XAie_TileLoc(24, 1));
	return;
  }

  void aie_graph_core_enable()
  {
	printf("Enabling core(s) of graph aie_graph...\n");
	XAie_CoreEnable(&DevInst, XAie_TileLoc(24,1 ));
	return;
  }

/************************** Partition reset *****************************/

  void resetPartition()
  {
    XAie_PartitionInitialize(&DevInst, nullptr);
  }


/************************** Error handling *****************************/

  void enableErrorHandling()
  {
    XAie_ErrorHandlingInit(&DevInst);
  }


/************************** Clock gating *****************************/

  void enableClockGating()
  {
    XAie_LocType locs[3] = {XAie_TileLoc(24, 1), XAie_TileLoc(19, 0), XAie_TileLoc(24, 0), };
    XAie_PmRequestTiles(&DevInst, locs, 3);

    XAie_TurnEccOn(&DevInst);
  }


/************************** Clear Partition Memories *****************************/

  void clearPartitionMems()
  {
    XAie_ClearPartitionMems(&DevInst);
  }


/************************** Collect Statically Allocated Resources *****************************/

  void dumpAllocatedRscsToFile(const std::string aieRscsFilePath)
  {
       XAie_SaveAllocatedRscsToFile(&DevInst, aieRscsFilePath.c_str());
  }


/************************** Graph Configurations  *****************************/

  adf::GraphConfig GraphConfigurations[] = {
  //{id, name, graphLoadElfFunc, graphInitFunc, graphDebugHalt, coreColumns, coreRows, iterMemColumns, iterMemRows, iterMemAddrs, triggered, plKernelInstanceNames, plAxiLiteModes, plDriverStartFuncs, plDriverCheckIPDoneFuncs}
    {0, "aie_graph", &aie_graph_load_elf, &aie_graph_init, &aie_graph_core_debug_halt, {24}, {0}, {24}, {0}, {0x4}, {0}, {}, {}, {}, {},  }, 
  };
  const int NUM_GRAPH = 1;

/************************** PLIO Configurations  *****************************/

  adf::PLIOConfig PLIOConfigurations[] = {
  //{id, name, loginal_name, shim_column, slaveOrMaster, streamId}
    {0, "aie_graph.in_kmeans", "in_plio_kmeans", 24, 0, 2},
    {1, "aie_graph.out_kmeans", "out_plio_kmeans", 24, 1, 0},
  };
  const int NUM_PLIO = 2;


/************************** AIE driver and ADF API initializer *****************************/

  class InitializeAIEControl
  {
  public:
    InitializeAIEControl()
    {
      printf("Initializing AIE driver...\n");
      XAie_SetupConfig(ConfigPtr, HW_GEN, XAIE_BASE_ADDR, XAIE_COL_SHIFT,
                       XAIE_ROW_SHIFT, XAIE_NUM_COLS, XAIE_NUM_ROWS,
                       XAIE_SHIM_ROW, XAIE_MEM_TILE_ROW_START,
                       XAIE_MEM_TILE_NUM_ROWS, XAIE_AIE_TILE_ROW_START,
                       XAIE_AIE_TILE_NUM_ROWS);

      XAie_CfgInitialize(&(DevInst), &ConfigPtr);

#if defined(__AIESIM__)
#if defined(__CDO__)
      XAie_SetIOBackend(&(DevInst), XAIE_IO_BACKEND_CDO); // Set aiengine driver library to run for CDO Mode
      XAie_UpdateNpiAddr(&(DevInst), 0xf70a0000);
#else
      //AIE driver currently error out XAie_UpdateNpiAddr for AIESIM
#endif
#else
      XAie_UpdateNpiAddr(&(DevInst), 0xf70a0000);
#endif

#if defined(__AIESIM__) && !defined(__CDO__)
      XAie_TurnEccOff(&DevInst);
#endif

      printf("Initializing ADF API...\n");

#if defined(__AIESIM__) && !defined(__CDO__)
      extern unsigned ess_debug;
#else
      unsigned ess_debug = false;
#endif

#ifdef __EXCLUDE_PL_CONTROL__
      bool exclude_pl_control = true;
#else
      bool exclude_pl_control = false;
#endif

#ifdef __CDO__
      int trace_config_stream_option = 2;
#else
      int trace_config_stream_option = 0;
#endif

      adf::initializeConfigurations(&DevInst, XAIE_NUM_COLS, XAIE_AIE_TILE_NUM_ROWS, XAIE_MEM_TILE_NUM_ROWS,
                                        GraphConfigurations, NUM_GRAPH,
                                        nullptr, 0,
                                        nullptr, 0,
                                        nullptr, 0,
                                        nullptr, 0,
                                        nullptr, 0,
                                        nullptr, 0,
                                        nullptr, 0,
                                        nullptr, 0,
                                        PLIOConfigurations, NUM_PLIO,
                                        nullptr, 0, trace_config_stream_option, nullptr,
                                        ess_debug, exclude_pl_control, true, &broadcastConfigForCoreEnable, true, 2);

    }
  } initAIEControl;



#if !defined(__CDO__)

// Kernel Stub Definition
  void kmeans_function(input_stream<int> *,output_stream<int> *) { /* Stub */ } 
#endif
