# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ulp_inst_0/ulp_inst_0.bd
# Block Designs: The module: 'ulp_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/ulp_inst_0/ip/ulp_inst_0_ip_pipe_dbg_hub_fw_00_0/ulp_inst_0_ip_pipe_dbg_hub_fw_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_ip_pipe_dbg_hub_fw_00_0 || ORIG_REF_NAME==ulp_inst_0_ip_pipe_dbg_hub_fw_00_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_ip_pipe_ext_tog_kernel_00_null_0/ulp_inst_0_ip_pipe_ext_tog_kernel_00_null_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_ip_pipe_ext_tog_kernel_00_null_0 || ORIG_REF_NAME==ulp_inst_0_ip_pipe_ext_tog_kernel_00_null_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_ip_pipe_ext_tog_kernel_01_null_0/ulp_inst_0_ip_pipe_ext_tog_kernel_01_null_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_ip_pipe_ext_tog_kernel_01_null_0 || ORIG_REF_NAME==ulp_inst_0_ip_pipe_ext_tog_kernel_01_null_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_ip_gnd_ext_tog_kernel_00_null_0/ulp_inst_0_ip_gnd_ext_tog_kernel_00_null_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_ip_gnd_ext_tog_kernel_00_null_0 || ORIG_REF_NAME==ulp_inst_0_ip_gnd_ext_tog_kernel_00_null_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_ip_gnd_ext_tog_kernel_01_null_0/ulp_inst_0_ip_gnd_ext_tog_kernel_01_null_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_ip_gnd_ext_tog_kernel_01_null_0 || ORIG_REF_NAME==ulp_inst_0_ip_gnd_ext_tog_kernel_01_null_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_dbg_hub_0/ulp_inst_0_axi_dbg_hub_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_dbg_hub_0 || ORIG_REF_NAME==ulp_inst_0_axi_dbg_hub_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_gpio_null_user_0/ulp_inst_0_axi_gpio_null_user_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_gpio_null_user_0 || ORIG_REF_NAME==ulp_inst_0_axi_gpio_null_user_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_user_0/ulp_inst_0_axi_ic_user_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_ic_user_0 || ORIG_REF_NAME==ulp_inst_0_axi_ic_user_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_user_extend_0/ulp_inst_0_axi_ic_user_extend_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_ic_user_extend_0 || ORIG_REF_NAME==ulp_inst_0_axi_ic_user_extend_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/ulp_inst_0_axi_noc_kernel0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_noc_kernel0_0 || ORIG_REF_NAME==ulp_inst_0_axi_noc_kernel0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_h2c_0/ulp_inst_0_axi_noc_h2c_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_noc_h2c_0 || ORIG_REF_NAME==ulp_inst_0_axi_noc_h2c_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_sc_plram_0/ulp_inst_0_axi_sc_plram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_sc_plram_0 || ORIG_REF_NAME==ulp_inst_0_axi_sc_plram_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_xlconcat_0_0/ulp_inst_0_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_xlconcat_0_0 || ORIG_REF_NAME==ulp_inst_0_xlconcat_0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_xlconstant_0_0/ulp_inst_0_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_xlconstant_0_0 || ORIG_REF_NAME==ulp_inst_0_xlconstant_0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_plram_ctrl_0/ulp_inst_0_plram_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_plram_ctrl_0 || ORIG_REF_NAME==ulp_inst_0_plram_ctrl_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_plram_ctrl_bram_0/ulp_inst_0_plram_ctrl_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_plram_ctrl_bram_0 || ORIG_REF_NAME==ulp_inst_0_plram_ctrl_bram_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_pipereg_kernel0_0/ulp_inst_0_pipereg_kernel0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_pipereg_kernel0_0 || ORIG_REF_NAME==ulp_inst_0_pipereg_kernel0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_pipereg_kernel1_0/ulp_inst_0_pipereg_kernel1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_pipereg_kernel1_0 || ORIG_REF_NAME==ulp_inst_0_pipereg_kernel1_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_pipereg_pcie0_0/ulp_inst_0_pipereg_pcie0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_pipereg_pcie0_0 || ORIG_REF_NAME==ulp_inst_0_pipereg_pcie0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_pipereg_pl_axi0_0/ulp_inst_0_pipereg_pl_axi0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_pipereg_pl_axi0_0 || ORIG_REF_NAME==ulp_inst_0_pipereg_pl_axi0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_reset_sync_kernel0_0/ulp_inst_0_reset_sync_kernel0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_reset_sync_kernel0_0 || ORIG_REF_NAME==ulp_inst_0_reset_sync_kernel0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_reset_sync_kernel1_0/ulp_inst_0_reset_sync_kernel1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_reset_sync_kernel1_0 || ORIG_REF_NAME==ulp_inst_0_reset_sync_kernel1_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_reset_sync_fixed_0/ulp_inst_0_reset_sync_fixed_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_reset_sync_fixed_0 || ORIG_REF_NAME==ulp_inst_0_reset_sync_fixed_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_rstn_const_0/ulp_inst_0_rstn_const_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_rstn_const_0 || ORIG_REF_NAME==ulp_inst_0_rstn_const_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_aie_prog_0/ulp_inst_0_axi_noc_aie_prog_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_noc_aie_prog_0 || ORIG_REF_NAME==ulp_inst_0_axi_noc_aie_prog_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_ai_engine_0_0/ulp_inst_0_ai_engine_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_ai_engine_0_0 || ORIG_REF_NAME==ulp_inst_0_ai_engine_0_0} -quiet] -quiet

# Block Designs: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_ai_engine_0_0/bd_0/bd_9d54.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9d54 || ORIG_REF_NAME==bd_9d54} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_ai_engine_0_0/bd_0/ip/ip_0/bd_9d54_noc_ai_mm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9d54_noc_ai_mm_0_0 || ORIG_REF_NAME==bd_9d54_noc_ai_mm_0_0} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_ai_engine_0_0/bd_0/ip/ip_1/bd_9d54_ai_pl_ch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9d54_ai_pl_ch_0_0 || ORIG_REF_NAME==bd_9d54_ai_pl_ch_0_0} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_ai_engine_0_0/bd_0/ip/ip_2/bd_9d54_pl_ai_ch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9d54_pl_ai_ch_0_0 || ORIG_REF_NAME==bd_9d54_pl_ai_ch_0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_dbg_fw_0/ulp_inst_0_axi_dbg_fw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_dbg_fw_0 || ORIG_REF_NAME==ulp_inst_0_axi_dbg_fw_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_const_1_0/ulp_inst_0_const_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_const_1_0 || ORIG_REF_NAME==ulp_inst_0_const_1_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_gate_dbgfw_or_0/ulp_inst_0_gate_dbgfw_or_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_gate_dbgfw_or_0 || ORIG_REF_NAME==ulp_inst_0_gate_dbgfw_or_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_setup_aie_0_0/ulp_inst_0_setup_aie_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_setup_aie_0_0 || ORIG_REF_NAME==ulp_inst_0_setup_aie_0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_sink_from_aie_0_0/ulp_inst_0_sink_from_aie_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_sink_from_aie_0_0 || ORIG_REF_NAME==ulp_inst_0_sink_from_aie_0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_dwc_setup_aie_0_s_0/ulp_inst_0_dwc_setup_aie_0_s_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_dwc_setup_aie_0_s_0 || ORIG_REF_NAME==ulp_inst_0_dwc_setup_aie_0_s_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_kernel_interrupt_xlconcat_0_In0_1_interrupt_concat_0/ulp_inst_0_kernel_interrupt_xlconcat_0_In0_1_interrupt_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_kernel_interrupt_xlconcat_0_In0_1_interrupt_concat_0 || ORIG_REF_NAME==ulp_inst_0_kernel_interrupt_xlconcat_0_In0_1_interrupt_concat_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_irq_const_tieoff_0/ulp_inst_0_irq_const_tieoff_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_irq_const_tieoff_0 || ORIG_REF_NAME==ulp_inst_0_irq_const_tieoff_0} -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_ai_engine_0_0/bd_0/bd_9d54_ooc.xdc

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ulp_inst_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_inst_0'. Do not add the DONT_TOUCH constraint.

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/output/ulp_inst_0_ooc_copy.xdc

# Block Designs: bd/ulp_inst_0/ulp_inst_0.bd
# Block Designs: The module: 'ulp_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/ulp_inst_0/ip/ulp_inst_0_ip_pipe_dbg_hub_fw_00_0/ulp_inst_0_ip_pipe_dbg_hub_fw_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_ip_pipe_dbg_hub_fw_00_0 || ORIG_REF_NAME==ulp_inst_0_ip_pipe_dbg_hub_fw_00_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_ip_pipe_ext_tog_kernel_00_null_0/ulp_inst_0_ip_pipe_ext_tog_kernel_00_null_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_ip_pipe_ext_tog_kernel_00_null_0 || ORIG_REF_NAME==ulp_inst_0_ip_pipe_ext_tog_kernel_00_null_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_ip_pipe_ext_tog_kernel_01_null_0/ulp_inst_0_ip_pipe_ext_tog_kernel_01_null_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_ip_pipe_ext_tog_kernel_01_null_0 || ORIG_REF_NAME==ulp_inst_0_ip_pipe_ext_tog_kernel_01_null_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_ip_gnd_ext_tog_kernel_00_null_0/ulp_inst_0_ip_gnd_ext_tog_kernel_00_null_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_ip_gnd_ext_tog_kernel_00_null_0 || ORIG_REF_NAME==ulp_inst_0_ip_gnd_ext_tog_kernel_00_null_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_ip_gnd_ext_tog_kernel_01_null_0/ulp_inst_0_ip_gnd_ext_tog_kernel_01_null_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_ip_gnd_ext_tog_kernel_01_null_0 || ORIG_REF_NAME==ulp_inst_0_ip_gnd_ext_tog_kernel_01_null_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_dbg_hub_0/ulp_inst_0_axi_dbg_hub_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_dbg_hub_0 || ORIG_REF_NAME==ulp_inst_0_axi_dbg_hub_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_gpio_null_user_0/ulp_inst_0_axi_gpio_null_user_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_gpio_null_user_0 || ORIG_REF_NAME==ulp_inst_0_axi_gpio_null_user_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_user_0/ulp_inst_0_axi_ic_user_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_ic_user_0 || ORIG_REF_NAME==ulp_inst_0_axi_ic_user_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_user_extend_0/ulp_inst_0_axi_ic_user_extend_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_ic_user_extend_0 || ORIG_REF_NAME==ulp_inst_0_axi_ic_user_extend_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_kernel0_0/ulp_inst_0_axi_noc_kernel0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_noc_kernel0_0 || ORIG_REF_NAME==ulp_inst_0_axi_noc_kernel0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_h2c_0/ulp_inst_0_axi_noc_h2c_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_noc_h2c_0 || ORIG_REF_NAME==ulp_inst_0_axi_noc_h2c_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_sc_plram_0/ulp_inst_0_axi_sc_plram_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_sc_plram_0 || ORIG_REF_NAME==ulp_inst_0_axi_sc_plram_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_xlconcat_0_0/ulp_inst_0_xlconcat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_xlconcat_0_0 || ORIG_REF_NAME==ulp_inst_0_xlconcat_0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_xlconstant_0_0/ulp_inst_0_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_xlconstant_0_0 || ORIG_REF_NAME==ulp_inst_0_xlconstant_0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_plram_ctrl_0/ulp_inst_0_plram_ctrl_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_plram_ctrl_0 || ORIG_REF_NAME==ulp_inst_0_plram_ctrl_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_plram_ctrl_bram_0/ulp_inst_0_plram_ctrl_bram_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_plram_ctrl_bram_0 || ORIG_REF_NAME==ulp_inst_0_plram_ctrl_bram_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_pipereg_kernel0_0/ulp_inst_0_pipereg_kernel0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_pipereg_kernel0_0 || ORIG_REF_NAME==ulp_inst_0_pipereg_kernel0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_pipereg_kernel1_0/ulp_inst_0_pipereg_kernel1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_pipereg_kernel1_0 || ORIG_REF_NAME==ulp_inst_0_pipereg_kernel1_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_pipereg_pcie0_0/ulp_inst_0_pipereg_pcie0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_pipereg_pcie0_0 || ORIG_REF_NAME==ulp_inst_0_pipereg_pcie0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_pipereg_pl_axi0_0/ulp_inst_0_pipereg_pl_axi0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_pipereg_pl_axi0_0 || ORIG_REF_NAME==ulp_inst_0_pipereg_pl_axi0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_reset_sync_kernel0_0/ulp_inst_0_reset_sync_kernel0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_reset_sync_kernel0_0 || ORIG_REF_NAME==ulp_inst_0_reset_sync_kernel0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_reset_sync_kernel1_0/ulp_inst_0_reset_sync_kernel1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_reset_sync_kernel1_0 || ORIG_REF_NAME==ulp_inst_0_reset_sync_kernel1_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_reset_sync_fixed_0/ulp_inst_0_reset_sync_fixed_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_reset_sync_fixed_0 || ORIG_REF_NAME==ulp_inst_0_reset_sync_fixed_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_rstn_const_0/ulp_inst_0_rstn_const_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_rstn_const_0 || ORIG_REF_NAME==ulp_inst_0_rstn_const_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_noc_aie_prog_0/ulp_inst_0_axi_noc_aie_prog_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_noc_aie_prog_0 || ORIG_REF_NAME==ulp_inst_0_axi_noc_aie_prog_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_ai_engine_0_0/ulp_inst_0_ai_engine_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_ai_engine_0_0 || ORIG_REF_NAME==ulp_inst_0_ai_engine_0_0} -quiet] -quiet

# Block Designs: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_ai_engine_0_0/bd_0/bd_9d54.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9d54 || ORIG_REF_NAME==bd_9d54} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_ai_engine_0_0/bd_0/ip/ip_0/bd_9d54_noc_ai_mm_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9d54_noc_ai_mm_0_0 || ORIG_REF_NAME==bd_9d54_noc_ai_mm_0_0} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_ai_engine_0_0/bd_0/ip/ip_1/bd_9d54_ai_pl_ch_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9d54_ai_pl_ch_0_0 || ORIG_REF_NAME==bd_9d54_ai_pl_ch_0_0} -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_ai_engine_0_0/bd_0/ip/ip_2/bd_9d54_pl_ai_ch_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9d54_pl_ai_ch_0_0 || ORIG_REF_NAME==bd_9d54_pl_ai_ch_0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_axi_dbg_fw_0/ulp_inst_0_axi_dbg_fw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_axi_dbg_fw_0 || ORIG_REF_NAME==ulp_inst_0_axi_dbg_fw_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_const_1_0/ulp_inst_0_const_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_const_1_0 || ORIG_REF_NAME==ulp_inst_0_const_1_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_gate_dbgfw_or_0/ulp_inst_0_gate_dbgfw_or_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_gate_dbgfw_or_0 || ORIG_REF_NAME==ulp_inst_0_gate_dbgfw_or_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_setup_aie_0_0/ulp_inst_0_setup_aie_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_setup_aie_0_0 || ORIG_REF_NAME==ulp_inst_0_setup_aie_0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_sink_from_aie_0_0/ulp_inst_0_sink_from_aie_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_sink_from_aie_0_0 || ORIG_REF_NAME==ulp_inst_0_sink_from_aie_0_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_dwc_setup_aie_0_s_0/ulp_inst_0_dwc_setup_aie_0_s_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_dwc_setup_aie_0_s_0 || ORIG_REF_NAME==ulp_inst_0_dwc_setup_aie_0_s_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_kernel_interrupt_xlconcat_0_In0_1_interrupt_concat_0/ulp_inst_0_kernel_interrupt_xlconcat_0_In0_1_interrupt_concat_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_kernel_interrupt_xlconcat_0_In0_1_interrupt_concat_0 || ORIG_REF_NAME==ulp_inst_0_kernel_interrupt_xlconcat_0_In0_1_interrupt_concat_0} -quiet] -quiet

# IP: bd/ulp_inst_0/ip/ulp_inst_0_irq_const_tieoff_0/ulp_inst_0_irq_const_tieoff_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_inst_0_irq_const_tieoff_0 || ORIG_REF_NAME==ulp_inst_0_irq_const_tieoff_0} -quiet] -quiet

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_ai_engine_0_0/bd_0/bd_9d54_ooc.xdc

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ulp_inst_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_inst_0'. Do not add the DONT_TOUCH constraint.

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/output/ulp_inst_0_ooc_copy.xdc
