# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_plram_ctrl_0/ulp_inst_0_plram_ctrl_0.xci
# IP: The module: 'ulp_inst_0_plram_ctrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_plram_ctrl_0/ulp_inst_0_plram_ctrl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_inst_0_plram_ctrl_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_plram_ctrl_0/ulp_inst_0_plram_ctrl_0.xci
# IP: The module: 'ulp_inst_0_plram_ctrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/users/eleonora.cabai/Documents/K-Means-AIE/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_plram_ctrl_0/ulp_inst_0_plram_ctrl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_inst_0_plram_ctrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
