catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project setup_aie
set_top setup_aie
# v++ -g, -D, -I, --advanced.prop kernel.setup_aie.kernel_flags
add_files "/home/users/eleonora.cabai/Documents/K-Means-AIE/data_movers/setup_aie.cpp" -cflags " -g"
open_solution -flow_target vitis solution
set_part xcvc1902-vsvd1760-2MP-e-S
create_clock -period 299.996999MHz -name default
# v++ -g or --profile_kernel stall
config_rtl -kernel_profile
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ -g
config_debug -enable
# v++ --advanced.param compiler.deadlockDetection
config_export -deadlock_detection sim
# v++ --advanced.param compiler.axiDeadLockFree
config_interface -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format xo -ipname setup_aie
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
