# This file was automatically generated by Vpl
write_user_impl_clock_constraint "top_i/ulp" "blp_s_aclk_kernel_00 {is_user_set true instance _bd_top port blp_s_aclk_kernel_00 clk_id 0 freq 200} blp_s_aclk_kernel_01 {is_user_set false instance _bd_top port blp_s_aclk_kernel_01 clk_id 1 freq 499.994999}" "" $vivado_output_dir "true"
